// Build-time translations keep both language pages usable without JavaScript.
// Every source fragment must exist, so English edits cannot silently drop a translation.
const translations = [
  ['<html lang="en">', '<html lang="ja">'],
  ['Gojūon — Japanese participant navigation for Moodle', 'Gojūon — Moodle の参加者を五十音で検索'],
  ['Find Moodle participants by their Japanese name readings. A familiar gojūon index, separate surname and given-name filters, and no core changes. Try the interactive demo.', 'Moodle の参加者を名前の読み方で検索。姓と名をそれぞれ五十音で絞り込める、コアの変更不要なプラグインです。デモでお試しください。'],
  ['Find participants by their Japanese names. A small Moodle plugin that makes a familiar task feel familiar again.', '日本語の名前には、五十音の索引を。Moodle の参加者を、名前の読み方から見つけられるプラグインです。'],
  ['Find participants by their Japanese names. Try the kana index demo.', '名前の読み方で参加者を検索。五十音フィルタをデモでお試しください。'],
  ['rel="canonical" href="https://moodle-gojuon.jethachan.net/"', 'rel="canonical" href="https://moodle-gojuon.jethachan.net/ja/"'],
  ['property="og:url" content="https://moodle-gojuon.jethachan.net/"', 'property="og:url" content="https://moodle-gojuon.jethachan.net/ja/"'],
  ['property="og:locale" content="en_US"', 'property="og:locale" content="ja_JP"'],
  ['Skip to content', '本文へスキップ'],
  ['aria-label="Main navigation"', 'aria-label="メインナビゲーション"'],
  ['aria-label="Gojūon home"', 'aria-label="Gojūon ホーム"'],
  ['>Try it</a>', '>デモ</a>'],
  ['>Install</a>', '>導入方法</a>'],
  ['aria-label="Language"', 'aria-label="表示言語"'],
  ['data-language="en" aria-current="page"', 'data-language="en"'],
  ['data-language="ja"', 'data-language="ja" aria-current="page"'],
  ['A small plugin for a more familiar Moodle', 'Moodle を、もっと使い慣れたかたちに'],
  ['Japanese names.<br>A Japanese index.', '日本語の名前には、<br>五十音の索引を。'],
  ['Find the person you’re looking for, by the way their name is read. Gojūon brings familiar kana navigation to your course participants page.', '探している人を、名前の読み方から。Gojūon は、コースの参加者ページに、使い慣れた五十音の索引を追加します。'],
  ['Try the kana index', '五十音フィルタを試す'],
  ['Download the plugin', 'プラグインをダウンロード'],
  ['Free &amp; open source', '無料・オープンソース'],
  ['No core changes', 'コアの変更不要'],
  ['Gojūon: an あ index card with a participant tab', 'Gojūon：参加者タブ付きの「あ」の索引カード'],
  ['The right starting point.', '名前の読み方が、出発点。'],
  ['01 / THE PROBLEM', '01 / こんな困りごとに'],
  ['You know the name.<br>The index should too.', '名前はわかる。<br>あとは、見つけるだけ。'],
  ['Moodle’s usual A–Z participant index looks at the written name. For a class full of names like <span lang="ja">佐藤</span>, <span lang="ja">鈴木</span>, and <span lang="ja">高橋</span>, Latin initials aren’t much help.', 'Moodle の標準的な A–Z 索引は、名前の表記をもとに参加者を絞り込みます。「佐藤」「鈴木」「高橋」のように漢字で登録された名前を探すとき、アルファベットの索引ではなかなか役に立ちません。'],
  ['The readings are already there in Moodle’s phonetic name fields. Gojūon puts them to work: choose <strong lang="ja">さ</strong> to find <strong lang="ja">佐藤（さとう）</strong>, or <strong lang="ja">た</strong> to find <strong lang="ja">高橋（たかはし）</strong>.', 'Moodle には、名前の読み方を登録するフィールドが用意されています。Gojūon はその情報を活用し、<strong>「さ」で佐藤（さとう）</strong>、<strong>「た」で高橋（たかはし）</strong>を見つけられるようにします。'],
  ['A familiar index. The participant list you already use.', 'いつもの参加者一覧に、使い慣れた索引を。'],
  ['02 / TRY IT YOURSELF', '02 / デモで試す'],
  ['Start with <span lang="ja">か</span>. Find Katō.', '「か」を選んで、加藤さんを探す。'],
  ['Choose a surname row, then narrow it down by given name.', 'まず姓の行を選び、次に名でさらに絞り込んでみてください。'],
  ['Interactive illustration', '操作できるデモ'],
  ['SAMPLE COURSE', 'サンプルコース'],
  ['Participants <span lang="ja">/ 参加者</span>', '参加者'],
  ['Reset filters', 'フィルタをリセット'],
  ['<span lang="ja">姓</span> Surname', '姓の読み方'],
  ['<span lang="ja">名</span> Given name', '名の読み方'],
  ['Latin initials A–Z', 'アルファベット A–Z'],
  ['Fictional course roster', '架空の参加者データ'],
  ['Participant results; scroll to see more names and columns', '参加者の検索結果。スクロールしてほかの参加者や列を表示できます'],
  ['Fictional participants matching the selected kana rows', '選択した五十音の行に該当する架空の参加者'],
  ['<th scope="col">Participant</th>', '<th scope="col">参加者</th>'],
  ['Surname reading', '姓の読み方'],
  ['Given-name reading', '名の読み方'],
  ['<th scope="col">Role</th>', '<th scope="col">ロール</th>'],
  ['Enable JavaScript to try the filters. The screenshots below show the plugin running in Moodle.', 'フィルタを試すには JavaScript を有効にしてください。下のスクリーンショットで、Moodle 上での動作をご覧いただけます。'],
  ['Sample data only. This illustration runs entirely in your browser.', 'サンプルデータのみを使用しています。このデモはブラウザ内で動作します。'],
  ['Try <strong lang="ja">か</strong> for Katō and Gotō, <strong lang="ja">さ</strong> for hiragana and half-width katakana, or <strong lang="ja">他</strong> for a missing reading. This is a simplified demonstration, not a live Moodle instance.', '<strong>「か」</strong>では加藤・後藤、<strong>「さ」</strong>ではひらがなと半角カタカナの読み方、<strong>「他」</strong>では読み方未登録の参加者を確認できます。これは機能を紹介する簡易デモで、実際の Moodle 環境ではありません。'],
  ['03 / A SMALL, CONSIDERED ADDITION', '03 / いつもの運用に、そのまま'],
  ['Fits the way your course works.', 'コースの使い方に、自然になじむ。'],
  ['Readings, not guesswork', '表記ではなく、読み方で'],
  ['Hiragana, katakana, half-width kana, and voiced variants belong to their familiar gojūon rows. Latin initials are available for romaji readings too.', 'ひらがな・カタカナ・半角カナ、濁音・半濁音も、対応する五十音の行にまとめます。ローマ字の読み方には、アルファベットの索引も使えます。'],
  ['Two ways to narrow it down', '姓と名、それぞれで絞り込み'],
  ['Filter surname and given name independently. Both work alongside Moodle’s existing participant filters, sorting, and pagination.', '姓と名を別々に指定して絞り込めます。Moodle の既存の参加者フィルタ、並べ替え、ページ切り替えと併用できます。'],
  ['Everyone has a place', '読み方がなくても、見つかる'],
  ['Missing or unclassified readings stay accessible under Other. Reading-based filters appear only when the viewer is permitted to see those fields.', '読み方が未登録、またはどの行にも該当しない参加者は「他」から確認できます。読み方によるフィルタは、その情報を閲覧できる利用者にのみ表示されます。'],
  ['04 / INSIDE MOODLE', '04 / MOODLE での表示'],
  ['The real thing.', '実際の画面をご覧ください。'],
  ['Actual plugin screenshots. Select an image to view it full size.', 'プラグインの実際のスクリーンショットです。画像を選ぶと、元のサイズで表示されます。'],
  ['Moodle participants page with separate surname and given-name kana filter bars', '姓と名の五十音フィルタを表示した Moodle の参加者ページ'],
  ['Moodle participant list filtered using the か surname row', '姓の「か」行で絞り込んだ Moodle の参加者一覧'],
  ['Familiar navigation', '使い慣れた五十音の索引'],
  ['Both kana index bars, right above the participant list.', '参加者一覧のすぐ上に、姓と名の五十音フィルタを表示。'],
  ['One row, the right people', '行を選ぶと、該当する参加者だけに'],
  ['The surname list narrowed down to the か row.', '姓の読み方が「か」行の参加者に絞り込んだ画面。'],
  ['05 / MAKE YOURSELF AT HOME', '05 / 導入方法'],
  ['A better index.<br>A simple install.', '探しやすく。<br>導入は、かんたんに。'],
  ['A local plugin for Moodle 4.5 and later.<br>No changes to Moodle core.', 'Moodle 4.5 以降に対応したローカルプラグインです。<br>Moodle コアの変更は不要です。'],
  ['Get the latest release', '最新リリースを入手'],
  ['GNU GPL v3 or later · PHP 8.3+', 'GNU GPL v3 以降 · PHP 8.3 以降'],
  ['Download the release ZIP', 'リリース ZIP をダウンロード'],
  ['Choose the packaged plugin ZIP attached to the GitHub release.', 'GitHub のリリースに添付されている、インストール用のプラグイン ZIP を選んでください。'],
  ['Install in Moodle', 'Moodle にインストール'],
  ['Go to <strong>Site administration → Plugins → Install plugins</strong>, upload the ZIP, and complete the upgrade.', '<strong>サイト管理 → プラグイン → プラグインをインストールする</strong>から ZIP をアップロードし、アップグレードを完了します。'],
  ['Set up your name readings', '名前の読み方を設定'],
  ['Populate participants’ phonetic name fields and include them in the applicable Moodle name display format. Gojūon respects their visibility.', '参加者の姓名の読み方フィールドに値を登録し、適用される Moodle の氏名表示フォーマットに含めてください。Gojūon は、その閲覧設定に従って動作します。'],
  ['You can hide the original A–Z bars in the plugin settings.', 'プラグインの設定で、標準の A–Z 索引を非表示にできます。'],
  ['Read the documentation ↗', 'ドキュメントを読む（英語）↗'],
  ['Find them by the way their name is read.', 'いつもの Moodle に、五十音の索引を。'],
  ['Made by <a href="https://jethachan.net">Jetha Chan</a>. An independent, open-source Moodle plugin.', '制作：<a href="https://jethachan.net">Jetha Chan</a>。独立して開発されたオープンソースの Moodle プラグインです。'],
  ['aria-label="Footer"', 'aria-label="フッター"'],
  ['>Source</a>', '>ソースコード</a>'],
  ['>Report an issue</a>', '>不具合を報告</a>'],
  ['>Licence</a>', '>ライセンス</a>'],
];

export function japanesePage(english) {
  let html = english;
  for (const [source, translated] of translations) {
    if (!html.includes(source)) throw new Error(`Missing translation source: ${source}`);
    html = html.replaceAll(source, translated);
  }
  return html;
}
